### PR TITLE
Fixed GitHub action for Python linting

### PR DESCRIPTION
**Pull request by douglascdev**
Fixed the GitHub action that automatically formats Python code using black and isort.

- I used [this](https://github.com/psf/black/actions/runs/17913292/workflow) as a template for the new workflow so I didn't use some of what was previously in the [workflow file](https://github.com/Snayff/nqp2/blob/develop/.github/workflows/lint_and_fix_py.yml), let me know if there's something that I should restore.
- I tested it on a fork before creating a branch here, so I believe it will work as long as the Workflow permissions are set correctly.
- I purposefully put an import in the wrong order on this PR to test if isort will fix it.

### CODE REVIEW

**Comment by douglascdev** [comment]
Looks like it works, the import was fixed :)

**Comment by snayff** [comment]
@douglascdev looks like it only checks to see if `black` flags any issues and errors if it does, rather than linting the file as it was before. We either need to :
1. Keep this **and** the previous version, but only apply the former to non-owners. 
2. Amend this to lint and update the files.

**Comment by douglascdev** [comment]
Did you have issues with the linting? From what I've tested, it should be linting just like you wanted, the -- check part is meant to avoid trying to commit a linted version if it's not necessary, when the files were already linted.

**Comment by snayff** [comment]
My build failed with the error stating that it "would" change files.
https://github.com/Snayff/nqp2/actions/workflows/lint_and_fix_py.yml

**Comment by douglascdev** [comment]
I see, [it's linting](https://github.com/Snayff/nqp2/pull/215/commits/4d980496cec831d106ecc15b86b6542464143d0f) but after the check step returns 1 the whole thing is flagged as failed anyway.
Adding `continue-on-error` to that step should do the trick to avoid incorrectly flagging the build, I'll test it again to make sure.

**Pull request merged**
